version: "3.8"

services:
  api:
    build:
      dockerfile: docker/Dockerfile
    command: uvicorn --factory app.app:create_app --reload --no-access-log --use-colors
    ports:
      - "8080:8080"
    env_file:
      - ./envs/base.env
      - ./envs/api.env
      - ./envs/base.overrides.env
      - ./envs/api.overrides.env
    volumes:
      - .:/app/
    init: true
    stdin_open: true
    tty: true
