name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  python_ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          make init
      - name: Run linters
        run: |
          make lint
      - name: Run tests
        run: |
          make test
